export const COUNTRIES = [
    { code: "af", dial: "+93", name: "Afghanistan" },
    { code: "al", dial: "+355", name: "Albania" },
    { code: "dz", dial: "+213", name: "Algeria" },
    { code: "ao", dial: "+244", name: "Angola" },
    { code: "ar", dial: "+54", name: "Argentina" },
    { code: "am", dial: "+374", name: "Armenia" },
    { code: "au", dial: "+61", name: "Australia" },
    { code: "at", dial: "+43", name: "Austria" },
    { code: "az", dial: "+994", name: "Azerbaijan" },
    { code: "bh", dial: "+973", name: "Bahrain" },
    { code: "bd", dial: "+880", name: "Bangladesh" },
    { code: "by", dial: "+375", name: "Belarus" },
    { code: "be", dial: "+32", name: "Belgium" },
    { code: "bz", dial: "+501", name: "Belize" },
    { code: "bo", dial: "+591", name: "Bolivia" },
    { code: "ba", dial: "+387", name: "Bosnia and Herzegovina" },
    { code: "bw", dial: "+267", name: "Botswana" },
    { code: "br", dial: "+55", name: "Brazil" },
    { code: "bn", dial: "+673", name: "Brunei" },
    { code: "bg", dial: "+359", name: "Bulgaria" },
    { code: "kh", dial: "+855", name: "Cambodia" },
    { code: "cm", dial: "+237", name: "Cameroon" },
    { code: "ca", dial: "+1", name: "Canada" },
    { code: "cl", dial: "+56", name: "Chile" },
    { code: "cn", dial: "+86", name: "China" },
    { code: "co", dial: "+57", name: "Colombia" },
    { code: "cd", dial: "+243", name: "Congo (DRC)" },
    { code: "cr", dial: "+506", name: "Costa Rica" },
    { code: "hr", dial: "+385", name: "Croatia" },
    { code: "cu", dial: "+53", name: "Cuba" },
    { code: "cy", dial: "+357", name: "Cyprus" },
    { code: "cz", dial: "+420", name: "Czech Republic" },
    { code: "dk", dial: "+45", name: "Denmark" },
    { code: "do", dial: "+1", name: "Dominican Republic" },
    { code: "ec", dial: "+593", name: "Ecuador" },
    { code: "eg", dial: "+20", name: "Egypt" },
    { code: "sv", dial: "+503", name: "El Salvador" },
    { code: "ee", dial: "+372", name: "Estonia" },
    { code: "et", dial: "+251", name: "Ethiopia" },
    { code: "fi", dial: "+358", name: "Finland" },
    { code: "fr", dial: "+33", name: "France" },
    { code: "ge", dial: "+995", name: "Georgia" },
    { code: "de", dial: "+49", name: "Germany" },
    { code: "gh", dial: "+233", name: "Ghana" },
    { code: "gr", dial: "+30", name: "Greece" },
    { code: "gt", dial: "+502", name: "Guatemala" },
    { code: "hn", dial: "+504", name: "Honduras" },
    { code: "hk", dial: "+852", name: "Hong Kong" },
    { code: "hu", dial: "+36", name: "Hungary" },
    { code: "is", dial: "+354", name: "Iceland" },
    { code: "in", dial: "+91", name: "India" },
    { code: "id", dial: "+62", name: "Indonesia" },
    { code: "ir", dial: "+98", name: "Iran" },
    { code: "iq", dial: "+964", name: "Iraq" },
    { code: "ie", dial: "+353", name: "Ireland" },
    { code: "il", dial: "+972", name: "Israel" },
    { code: "it", dial: "+39", name: "Italy" },
    { code: "jm", dial: "+1", name: "Jamaica" },
    { code: "jp", dial: "+81", name: "Japan" },
    { code: "jo", dial: "+962", name: "Jordan" },
    { code: "kz", dial: "+7", name: "Kazakhstan" },
    { code: "ke", dial: "+254", name: "Kenya" },
    { code: "kw", dial: "+965", name: "Kuwait" },
    { code: "kg", dial: "+996", name: "Kyrgyzstan" },
    { code: "lv", dial: "+371", name: "Latvia" },
    { code: "lb", dial: "+961", name: "Lebanon" },
    { code: "ly", dial: "+218", name: "Libya" },
    { code: "lt", dial: "+370", name: "Lithuania" },
    { code: "lu", dial: "+352", name: "Luxembourg" },
    { code: "mg", dial: "+261", name: "Madagascar" },
    { code: "my", dial: "+60", name: "Malaysia" },
    { code: "mv", dial: "+960", name: "Maldives" },
    { code: "mt", dial: "+356", name: "Malta" },
    { code: "mu", dial: "+230", name: "Mauritius" },
    { code: "mx", dial: "+52", name: "Mexico" },
    { code: "md", dial: "+373", name: "Moldova" },
    { code: "mn", dial: "+976", name: "Mongolia" },
    { code: "ma", dial: "+212", name: "Morocco" },
    { code: "mz", dial: "+258", name: "Mozambique" },
    { code: "mm", dial: "+95", name: "Myanmar" },
    { code: "na", dial: "+264", name: "Namibia" },
    { code: "np", dial: "+977", name: "Nepal" },
    { code: "nl", dial: "+31", name: "Netherlands" },
    { code: "nz", dial: "+64", name: "New Zealand" },
    { code: "ni", dial: "+505", name: "Nicaragua" },
    { code: "ng", dial: "+234", name: "Nigeria" },
    { code: "no", dial: "+47", name: "Norway" },
    { code: "om", dial: "+968", name: "Oman" },
    { code: "pk", dial: "+92", name: "Pakistan" },
    { code: "pa", dial: "+507", name: "Panama" },
    { code: "py", dial: "+595", name: "Paraguay" },
    { code: "pe", dial: "+51", name: "Peru" },
    { code: "ph", dial: "+63", name: "Philippines" },
    { code: "pl", dial: "+48", name: "Poland" },
    { code: "pt", dial: "+351", name: "Portugal" },
    { code: "qa", dial: "+974", name: "Qatar" },
    { code: "ro", dial: "+40", name: "Romania" },
    { code: "ru", dial: "+7", name: "Russia" },
    { code: "rw", dial: "+250", name: "Rwanda" },
    { code: "sa", dial: "+966", name: "Saudi Arabia" },
    { code: "sn", dial: "+221", name: "Senegal" },
    { code: "rs", dial: "+381", name: "Serbia" },
    { code: "sg", dial: "+65", name: "Singapore" },
    { code: "sk", dial: "+421", name: "Slovakia" },
    { code: "si", dial: "+386", name: "Slovenia" },
    { code: "so", dial: "+252", name: "Somalia" },
    { code: "za", dial: "+27", name: "South Africa" },
    { code: "kr", dial: "+82", name: "South Korea" },
    { code: "ss", dial: "+211", name: "South Sudan" },
    { code: "es", dial: "+34", name: "Spain" },
    { code: "lk", dial: "+94", name: "Sri Lanka" },
    { code: "sd", dial: "+249", name: "Sudan" },
    { code: "se", dial: "+46", name: "Sweden" },
    { code: "ch", dial: "+41", name: "Switzerland" },
    { code: "sy", dial: "+963", name: "Syria" },
    { code: "tw", dial: "+886", name: "Taiwan" },
    { code: "tj", dial: "+992", name: "Tajikistan" },
    { code: "tz", dial: "+255", name: "Tanzania" },
    { code: "th", dial: "+66", name: "Thailand" },
    { code: "tn", dial: "+216", name: "Tunisia" },
    { code: "tr", dial: "+90", name: "Turkey" },
    { code: "tm", dial: "+993", name: "Turkmenistan" },
    { code: "ug", dial: "+256", name: "Uganda" },
    { code: "ua", dial: "+380", name: "Ukraine" },
    { code: "ae", dial: "+971", name: "United Arab Emirates" },
    { code: "gb", dial: "+44", name: "United Kingdom" },
    { code: "us", dial: "+1", name: "United States" },
    { code: "uy", dial: "+598", name: "Uruguay" },
    { code: "uz", dial: "+998", name: "Uzbekistan" },
    { code: "ve", dial: "+58", name: "Venezuela" },
    { code: "vn", dial: "+84", name: "Vietnam" },
    { code: "ye", dial: "+967", name: "Yemen" },
    { code: "zm", dial: "+260", name: "Zambia" },
    { code: "zw", dial: "+263", name: "Zimbabwe" },
] as const;

export type Country = typeof COUNTRIES[number];
